### ISSUE TITLE
Prosessere data fra CVPartner

### ISSUE THREAD

**Issue by TrymVei** [varianter/chewbacca#10]
Før vi kan lagra dataen til databasen trenger vi å prosessere dataen vi får fra CVPartner(CVPartnerDTO) og gjøre det om til en Employee. Vi må finne ut hvilken data vi ønsker å ha med

**Comment by TrymVei** [comment]
- [ ] Hente data fra CvPartner
- [ ] Formatere data
- [ ] Legge til/oppdatere databasen

**Comment by strombraaten** [comment]
Fullføres når #32 blir ferdig
