### ISSUE TITLE
Periodisk uthenting av data

### ISSUE THREAD

**Issue by tormodhau** [varianter/chewbacca#20]
Sette opp periodisk uthenting av data fra CV-partner

Undersøk om det finnes en Scheduler innebygd i .Net Core som vi kan bruke.

**Comment by TrymVei** [comment]
https://www.quartz-scheduler.net/

**Comment by nikolaia** [comment]
Noterer ned det vi har skrevet om tidligere: Tenker at prosessen burde trigges av et API-endepunkt, og at scheduling trekkes helt ut som et separat problem. Feks kunne vi kjørt opp en Azure Functions app på samme App Plan som Chewbacca som bruker Timer trigger til å kalle APIet som starter uthentingen: https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-timer

**Comment by nikolaia** [comment]
Kan gjøres så enkelt som dette og: https://github.com/kdcllc/CronScheduler.AspNetCore
