### ISSUE TITLE
Legge nøkkel for CV-Partner i Azure Key Vault

### ISSUE THREAD

**Issue by tormodhau** [varianter/chewbacca#21]
Parent: https://github.com/varianter/chewbacca/issues/11

Per i dag settes tilgangsnøkkel for CV-partner legges i en appsettings.local.json. For produksjonsmiljøet skal denne inn i Azure Key Vault og hentes derfra.

**Comment by nikolaia** [comment]
Har en plan for hvordan vi best fikser det med secrets i KeyVault. Skal ta postgres-connectionstringen til Bemanning inn der i samme slengen 👍 mtp #22
