### ISSUE TITLE
Filtrere ansatte basert på start- og slutt-dato fra bemanning

### ISSUE THREAD

**Issue by mikaelbr** [varianter/chewbacca#22]
- Hent start og sluttdato for alle ansatte fra Bemanning sammen (gjøres sammen med periodisk uthenting av ansatte)
- Legge til start- og sluttdato i Employee-modellen
- Lag endepunkt som kun leverer Employees som har startet

**Comment by nikolaia** [comment]
I dag filterer Chewbacca ut enddate i spørringen mot bemanningsdatabasen. Vi burde hente ut alle og heller filtrere ut i chewbacca, slik at de som slutter i fremtiden faktisk forsvinner fra API-endepunktet (ikke bare slutter å bli oppdatert fra bemanning)

**Comment by nikolaia** [comment]
Gjort, men rydder ikke opp blob
