### ISSUE TITLE
Bruke epost for å identifisere brukere ved lagring fra CVPartner

### ISSUE THREAD

**Issue by tormodhau** [varianter/chewbacca#32]
Når vi får en bruker fra CvPartner
Sjekk i databasen om vi allerede har lagret en bruker med samme epost
Dersom eposten finnes, oppdater brukeren i basen, hvis ikke legg til

Oppgaver
* (opprydding) Fjern ID-feltet fra Employee-modellen
* I EmployeeRepository.AddOrUpdate(Employee): hent ut employees med epost, og oppdatert hvis får treff, ellers lagre som ny.

Eksperimenter:
* Forsøk å lagre en EmployeeEntity
* * Uten ID
* * Med ID som finnes i DB
* * Med ID som ikke finnes i DB

https://learn.microsoft.com/en-us/ef/core/

**Comment by TrymVei** [comment]
Ligger nå inne i https://github.com/varianter/chewbacca/tree/Service-CVPartner

**Comment by strombraaten** [comment]
Gjenstår å finpusse litt på koden, sjekker opp med @nikolaia angående å pushe til prod når det er klart.

**Comment by nikolaia** [comment]
Databasen har en unik ID, men nå også en unique index på epost ✅
