### ISSUE TITLE
Bruke Managed Identity for å snakke med bemanningsdatabasen

### ISSUE THREAD

**Issue by nikolaia** [varianter/chewbacca#55]
Vi bruker username/password/secret i dag, men Postgres i Azure støtter Managed Identity (som chewbacca har): https://learn.microsoft.com/EN-us/azure/postgresql/single-server/how-to-connect-with-managed-identity

**Comment by mikaelbr** [comment]
Bemanning bruker Postgres på AWS via Heroku, sammenstilt med samme pipelines for kunder som kjører egen utgave av bemanning

**Comment by nikolaia** [comment]
Skjønner, da dropper vi det :)
