### ISSUE TITLE
Forbedre Auth / OAuth2

### ISSUE THREAD

**Issue by nikolaia** [varianter/chewbacca#93]
I dag godtar vi alle tokens signert av vår AzureAD tenant. Vi burde fikse scope og audience for å snevre inn at det faktisk er tokens gitt til de rette brukerene i de rette contextene for å kalle Chewbacca.

Det er laget en app registration og et scope allerede, som bare må valideres mot: https://portal.azure.com/#view/Microsoft_AAD_RegisteredApps/ApplicationMenuBlade/~/Overview/appId/d20d1879-ce90-4079-a4cb-52a520993c66/isMSAApp~/false

**Comment by haakoaho** [comment]
Dette vil påvirke alle konsumenter som bruker Chewbacca varianter/variant-rocks med flere.
